gem "crack", :git => "http://github.com/jnunemaker/crack.git"
gem "httparty", :git => "http://github.com/jnunemaker/httparty.git"
gem "rack", :git => "http://github.com/rack/rack.git"
gem "sinatra", :git => "http://github.com/sinatra/sinatra.git"
gem "rdiscount", :git => "http://github.com/rtomayko/rdiscount.git"
