gem "haml", :git => "http://github.com/nex3/haml.git"
gem "crack", :git => "http://github.com/jnunemaker/crack.git"
gem "httparty", :git => "http://github.com/jnunemaker/httparty.git"
gem "sinatra", :git => "http://github.com/sinatra/sinatra.git"
gem "rdiscount", :git => "http://github.com/rtomayko/rdiscount.git"
gem "dalli", :git => "http://github.com/mperham/dalli.git"
source "http://rubygems.org/"
gem "builder"
gem "rack"
